home_top/urls.py
from django import views
from django.urls import path
from . import views
 
app_name = 'home'

urlpatterns = [
    path('top/', views.ModelDetailList.as_view(), name='home_top'),
    path('top/detail/motion/<int:pk>/', views.Motion_ModelDetailView, name='motion_detail'),
    path('top/detail/culture/<int:pk>/', views.Culture_ModelDetailView.as_view(), name='culture_detail'),
]

wa/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home_top.urls'))
]

home_top/models.py
from django.db import models

class Event_Model(models.Model):
    name = models.CharField(max_length=255)
    images = models.CharField(max_length=100)
    
class Event_Motion_Model(models.Model):
    name = models.CharField(max_length=255)
    images = models.CharField(max_length=100)

home_top/views.py
from imp import new_module
import math
from pickle import NONE
from django.shortcuts import render
from requests import request
from .list import Event_List, Sports_List
from .models import Event_Model,Event_Motion_Model
from django.views.generic import View, TemplateView, ListView, DetailView

#トップページ
class ModelDetailList(ListView):
    model = Event_Motion_Model
    template_name = 'templates/home/home.html'
        
    def get_context_data(self, *args, **kwargs):
        motion_model = Event_Motion_Model.objects.all()
        if motion_model is NONE:
            #運動系の名前,写真をDBに挿入
            event_list_motion = Event_List.Event_List_Motion
            Event_Motion_Model.objects.all().delete()
            for event in event_list_motion:
                event_name = event[0]
                event_img = event[1]
                events =  Event_Motion_Model(name = event_name, images = event_img)
                events.save()
            #文科系の名前,写真をDBに挿入
            event_list_culture = Event_List.Event_List_Culture
            Event_Model.objects.all().delete()
            for event in event_list_culture:
                event_name = event[0]
                event_img = event[1]
                events =  Event_Model(name = event_name, images = event_img)
                events.save()
        
        #運動系のDBを使用可能
        context = super().get_context_data(*args, **kwargs)
        context['culture_list'] = Event_Model.objects.all
        return context

#運動系検索ページ
def Motion_ModelDetailView(request,pk):
    model_id = pk
    if model_id == 1:
        sports_list = Sports_List.Ball_Sports
    elif model_id == 2:
        sports_list = Sports_List.Indoor_Sports 
    elif model_id == 3:
        sports_list = Sports_List.Outdoor_Sports
    elif model_id == 4:
        sports_list = Sports_List.Winter_Sports
    else:
        sports_list = Sports_List.Other_Sports
    
    event_motion_model = Event_Motion_Model.objects.all().values()
    
    context = {
                'sports_list':sports_list,
                'event_motion_model':event_motion_model
               }
    return render(request, 'templates/home/detail.html', context)

#文科系詳細ページ
class Culture_ModelDetailView(DetailView):
    model = Event_Model
    template_name = 'templates/home/detail.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['culture_list'] = Event_Model.objects.all().values()
        return context
    
    

templates/header/header.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'header/header.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14" ></script>
    <script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <header class="header">
        <img src= "{% static 'header/header-img/circle_of_waseda.png' %}" alt="logo" class="logo">
        <nav class="nav-header-item">
            <li><a href="{% url 'home:home_top' %}">login</a></li>
            <li><a href="{% url 'home:home_top' %}">signup</a></li>
            <!--ハンバーガーメニュー-->
            <li>
                <div id="navArea">
                    <nav class="nav-header-hum">
                        <div class="inner-header-hum">
                            <ul class="inner-header-hum-ul">
                                <li><a href="#">aa</a></li>
                                <li><a href="#">bb</a></li>
                                <li><a href="#">cc</a></li>
                            </ul>
                        </div>
                    </nav>
                    <!--ハンバーガーメニューボタン-->
                    <button type="button" class="toggle-btn-header">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>

                        <!--ハンバーガーメニュー背景-->
                    <div id="mask"></div>
                </div>
            </li>
        </nav>
    </header>
    

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>
    <script src="{% static 'header/header.js' %}"></script>
</body>
</html>

templates/home/detail.html
{% extends './../header/header.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'home/detail.css' %}">
{% endblock %}

{% block content %}
<div id="app">
    <ul class="sports-list">
        <!--スポーツ名-->
        {% for list in sports_list %}
        <li class="sports-list-li">
            <input type="checkbox" id="{{list}}" v-model="items" value="{{ list }}">
            <label for="{{list}}">{{list}}</label>
        </li>
        {% endfor %}
    </ul>


    <template v-for="item in items">
        [[item]]
    </template>

    <!--サークル一覧-->
    {% for list in sports_list %}
    <ul>
        <template v-for="item in items">
            <li v-if="'{{list}}' == item">cc</li>
        </template>
    </ul>
    {% endfor %}
</div>


<script src="{% static 'home/detail.js' %}"></script>
{% endblock %}

templates/home/home.html
{% extends './../header/header.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="./../../static/home/home.css">
{% endblock %}

{% block content %}
<!--ファーストイメージ-->
<img src="{% static 'home/home-img/waseda.png' %}" alt="waseda">


<div id="app">
    <div class="first-circle"></div>
    <div class="top-square"></div>
    <div class="right-triangle" ></div>
    <div class="bottom-square"></div>
    <div class="left-triangle" ></div>
    <div class="container"></div>
</div>



<!--サイト紹介-->
<strong >
    <div class="introduction">
        <h2 class="introduction-title">contents</h2>
        <ul class="introduction-contents">
            <li>
                <div class="introduction-contents-item-1">
                    <h2>サークルをお探しの方へ</h2>
                    <p>texttexttexttexttexttexttexttexttexttext
                    texttexttexttexttexttexttexttexttexttext
                    texttexttexttexttexttexttexttexttexttext
                    texttexttexttexttexttext</p>
                </div>
            </li>
            <li>
                <div class="introduction-contents-item-2">
                    <h2>サークル長へ</h2>
                    <p>texttexttexttexttexttexttexttexttexttext
                        texttexttexttexttexttext</p>
                </div>
            </li>
        </ul>
    </div>
</strong>


<!--検索-->
<strong class="circle-search" >
    <div>
        <h2>circle search</h2>
        <ul class="circle-type">
            <li>
                <!--運動系検索-->
                <p>運動系</p>
                <ul class="circle-type-item">
                    {% for lists in object_list %}
                    <li>
                        <button onclick="location.href='detail/motion/{{ lists.id }}'">
                            <ul class="circle-type-item-list">
                                <li><img src= {{lists.images}} alt="img"></li>
                                <li><p>{{lists.name}}</p></li>
                            </ul>
                        </button>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            <!--文科系検索-->
            <li>
                <p>文科系</p>
                <ul class="circle-type-item">
                    {% for lists in culture_list %}
                    <li>
                        <button onclick="location.href='detail/culture/{{ lists.id }}'">
                            <ul class="circle-type-item-list">
                                <li><img src= {{lists.images}} alt="img"></li>
                                <li><p>{{lists.name}}</p></li>
                            </ul>
                        </button>
                    </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    </div>
</strong>


<script src="https://unpkg.com/scrollreveal"></script>
<script src="{% static 'home/home.js' %}" ></script>
{% endblock %}